_config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django import views as django_views

urlpatterns = [
    path('', include('review.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), 
    url(r'^jsi18n/$', django_views.i18n.JavaScriptCatalog.as_view(), name='jsi18n'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {
            'document_root': os.path.join(BASE_DIR, 'site'),
            'show_indexes': True
        },
        name='site_path'
    ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(BASE_DIR, 'review/static'),
    }),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login)))
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

foods/urls.py
from django.urls import path
from . import views

app_name = 'foods'
urlpatterns = [

    path('', views.FoodLanding.as_view(), name='food_landing'),
    # path('main/create', views.CatCreate.as_view(), name='cat_create'),
    # path('main/<int:pk>/update', views.CatUpdate.as_view(), name='cat_update'),
    # path('main/<int:pk>/delete', views.CatDelete.as_view(), name='cat_delete'),

    # path('lookup', views.BreedView.as_view(), name='breed_list'),
    # path('lookup/create', views.BreedCreate.as_view(), name='breed_create'),
    # path('lookup/<int:pk>/update', views.BreedUpdate.as_view(), name='breed_update'),
    # path('lookup/<int:pk>/delete', views.BreedDelete.as_view(), name='breed_delete')
]

review/urls.py
from django import views
from django.urls import path
from .import views

app_name = 'review'
urlpatterns = [
    path('', views.ReviewLanding.as_view(), name='review_landing'),
    path('wiki_foods', views.FoodListView.as_view(), name='wiki_foods'),
    path('wiki_food/<int:pk>', views.FoodMetadataUpdate.as_view(), name='food_metadata'),
    path('pair_usda/<int:pk>', views.UsdaPairingView.as_view(), name='pair_usda'),

    path('wiki_categories', views.CategoriesListView.as_view(), name='wiki_categories'),
    path('wiki_category/<int:pk>', views.CategoryMetadataUpdate.as_view(), name='wiki_category'),

    path('pair/<int:pk>', views.PairedFoodView.as_view(), name='paired_food'),
    path('paired', views.PairedListView.as_view(), name='paired'),
    path('indexed', views.IndexedListView.as_view(), name='indexed'),
    
    path('food_scrape', views.ScrapeFood.as_view(), name='food_scrape'),
    path('category_scrape', views.ScrapeCategories.as_view(), name='category_scrape'),
    path('category_scrape/<int:pk>', views.ScrapeCategory.as_view(), name='test'),
    path('batch', views.Batch.as_view(), name='batch'),
    path('todos', views.TodoPage.as_view(), name='todos'),
]

review/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.utils.translation import gettext_lazy as _


####################
# Wikipedia Models #
####################


class WikiCategory(models.Model):
    name = models.CharField(
        max_length=200,
        blank=False,
        validators=[MinLengthValidator(2)]
    )
    description = models.CharField(max_length=30000)
    wiki_url = models.CharField(max_length=1000, null=True)
    parent_category = models.ForeignKey(
        'WikiCategory', on_delete=models.SET_NULL, null=True)
    foods = models.ManyToManyField(
        'WikiFood', through='WikiCategoryAssignment', blank=True)

    def __str__(self):
        return self.name


class WikiFood(models.Model):
    name = models.CharField(
        max_length=200,
        blank=False,
        validators=[MinLengthValidator(2)]
    )
    description = models.CharField(max_length=30000)
    wiki_url = models.CharField(max_length=1000, unique=True)
    img_src = models.CharField(max_length=1000, null=True)
    categories = models.ManyToManyField(
        'WikiCategory', through='WikiCategoryAssignment', blank=True)

    def __str__(self):
        return self.name


class WikiFoodName(models.Model):

    class Meta:
        unique_together = (('name', 'type', 'food'),)

    food = models.ForeignKey(WikiFood, on_delete=models.CASCADE)
    name = models.CharField(max_length=500)

    class NameType(models.TextChoices):
        INFOBOX = 'IN', _('infobox')
        SCIENTIFIC = 'SC', _('scientific')
        BOLD = 'BL', _('bold')
        PAGETITLE = 'PT', _('pageTitle')

    type = models.CharField(
        max_length=2,
        choices=NameType.choices,
        default=NameType.INFOBOX,
    )


class WikiCategoryAssignment(models.Model):
    class Meta:
        unique_together = (('food', 'category'),)

    food = models.ForeignKey(WikiFood, on_delete=models.CASCADE)
    category = models.ForeignKey(WikiCategory, on_delete=models.CASCADE)

###############
# USDA Models #
###############

# 'Survey (FNDDS)' | 'Branded' | 'Foundation' | 'SR Legacy'
# class UsdaDBSource(models.Model):
#     source = models.CharField(max_length=200)


class UsdaFood(models.Model):
    fdc_id = models.CharField(max_length=20, unique=True, primary_key=True)
    description = models.CharField(max_length=20000)

    # 'Survey (FNDDS)' | 'Branded' | 'Foundation' | 'SR Legacy'
    dataType = models.CharField(max_length=200)
    foodClass = models.CharField(max_length=200)
    foodCode = models.CharField(max_length=20, null=True)  # FNDDS id
    totalRefuse = models.CharField(max_length=20, null=True)
    ingredients = models.CharField(max_length=20000, null=True)
    scientificName = models.CharField(max_length=500, null=True)
    category = models.CharField(max_length=500, null=True)

    # GTIN or UPC code identifying the food. Only applies to Branded Foods.
    gtinUpc = models.CharField(max_length=20, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # finalFoodInputFoods?: FinalFoodInputFoods[]
    # foodComponents?: any[] // ??

    def __str__(self):
        return self.fdc_id


class UsdaWikiPairing(models.Model):

    class Meta:
        unique_together = (('usda_food', 'wiki_food'),)

    usda_food = models.ForeignKey(UsdaFood, on_delete=models.CASCADE)
    wiki_food = models.ForeignKey(WikiFood, on_delete=models.CASCADE)
    indexed = models.BooleanField(default=False)
    data = {}

    def set_data(self, key, value):
        self.data = {key: value}

    def __str__(self):
        return self.wiki_food.name


class UsdaNutrient(models.Model):
    class Meta:
        unique_together = (('number', 'unitName'),)

    number = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    rank = models.PositiveSmallIntegerField(null=True)
    unitName = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class UsdaFoodNutrient(models.Model):
    amount = models.FloatField()
    nutrient = models.ForeignKey(UsdaNutrient, on_delete=models.CASCADE)
    usda_food = models.ForeignKey(UsdaFood, on_delete=models.CASCADE)

    def __str__(self):
        return self.usda_food.description + ' | ' + str(self.amount) + ' ' + self.nutrient.unitName + ' ' + self.nutrient.name


class UsdaFoodPortion(models.Model):

    class Meta:
        unique_together = (('portionDescription', 'usda_food'),)

    portionDescription = models.CharField(max_length=200, null=True)
    modifier = models.CharField(max_length=100)
    gramWeight = models.CharField(max_length=20)
    sequenceNumber = models.PositiveIntegerField(null=True)
    usda_food = models.ForeignKey(UsdaFood, on_delete=models.CASCADE)

    def __str__(self):
        return self.portionDescription


####################
# Photo API Models #
####################

class UnsplashPhoto(models.Model):

    @property
    def src(self):
        return self.full

    @property
    def thumb(self):
        return self.thumb

    class Meta:
        unique_together = (('search_term', 'order', 'food'),)

    source = 'unsplash'
    food = models.ForeignKey(WikiFood, on_delete=models.CASCADE)
    # Search term used to discover this photo
    search_term = models.CharField(max_length=100)
    order = models.IntegerField()  # The order in which the photo was provided
    total = models.IntegerField()  # The total number of photos found from this search
    width = models.IntegerField()
    height = models.IntegerField()
    color = models.CharField(max_length=20)
    blur_hash = models.CharField(
        max_length=500, null=True)  # https://blurha.sh/
    description = models.CharField(max_length=1500, null=True)
    alt_description = models.CharField(max_length=1500, null=True)
    raw = models.CharField(max_length=500, null=True)
    full = models.CharField(max_length=500, null=True)
    thumb = models.CharField(max_length=500, null=True)
    small = models.CharField(max_length=500, null=True)
    regular = models.CharField(max_length=500, null=True)
    unsplash_page = models.CharField(max_length=500, null=True)
    username = models.CharField(max_length=100, null=True)
    ancestryCategory = models.CharField(max_length=100, null=True)
    ancestrySubcategory = models.CharField(max_length=100, null=True)


class PexelsPhoto(models.Model):

    @property
    def src(self):
        return self.original

    @property
    def thumb(self):
        return self.tiny

    class Meta:
        unique_together = (('search_term', 'order', 'food'),)

    source = 'pexels'
    food = models.ForeignKey(WikiFood, on_delete=models.CASCADE)
    # Search term used to discover this photo
    search_term = models.CharField(max_length=100)
    order = models.IntegerField()  # The order in which the photo was provided
    total = models.IntegerField()  # The total number of photos found from this search
    pexels_id = models.IntegerField()
    width = models.IntegerField()
    height = models.IntegerField()
    url = models.CharField(max_length=100)
    photographer = models.CharField(max_length=30)
    photographer_url = models.CharField(max_length=100)
    photographer_id = models.IntegerField()
    avg_color = models.CharField(max_length=10)
    original = models.CharField(max_length=200)

    large2x = models.CharField(max_length=200)
    small = models.CharField(max_length=200)
    tiny = models.CharField(max_length=200)
    # large = models.CharField(max_length=200)
    # medium = models.CharField(max_length=200)
    # portrait = models.CharField(max_length=200)
    # landscape = models.CharField(max_length=200)


class PixabayPhoto(models.Model):

    @property
    def src(self):
        return self.imageURL

    @property
    def thumb(self):
        return self.previewURL
    class Meta:
        unique_together = (('search_term', 'order', 'food'),)

    source = 'pixabay'
    food = models.ForeignKey(WikiFood, on_delete=models.CASCADE)
    # Search term used to discover this photo
    search_term = models.CharField(max_length=100)
    order = models.IntegerField()  # The order in which the photo was provided
    total = models.IntegerField()  # The total number of photos found from this search

    pageURL = models.CharField(max_length=100)
    pixabay_id = models.IntegerField()
    tags = models.CharField(max_length=100)
    previewWidth = models.IntegerField()
    previewHeight = models.IntegerField()
    webformatWidth = models.IntegerField()
    webformatHeight = models.IntegerField()
    largeImageURL = models.CharField(max_length=200)  # this is the best one
    imageURL = models.CharField(max_length=200)
    imageWidth = models.IntegerField()
    imageHeight = models.IntegerField()
    imageSize = models.IntegerField()
    views = models.IntegerField()
    downloads = models.IntegerField()
    favorites = models.IntegerField()
    likes = models.IntegerField()
    comments = models.IntegerField()
    user_id = models.IntegerField()
    user = models.CharField(max_length=30)
    previewURL = models.CharField(max_length=200)
    # fullHDURL = models.CharField(max_length=200)
    # webformatURL = models.CharField(max_length=200)


##################################
# Model to hold Scrappable pages #
##################################

class Scrapable(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=1000, unique=True)
    column = models.PositiveSmallIntegerField(null=True, default=0)
    isCategory = models.BooleanField(default=True)
    type = models.CharField(max_length=20)

    scraped = models.BooleanField(default=False)
    food_count = models.PositiveIntegerField(null=True)

    @property
    def uri(self):
        return self.url.split('/')[-1].replace('_', ' ')


#####################################
# Finalized Food and Nutrition Data #
#####################################

review/views/complete_views.py
import re
from django.shortcuts import redirect, render
from django.urls.base import reverse_lazy
from django.views import View
from review.models import UsdaFoodNutrient, UsdaWikiPairing, WikiFood
from pydash import py_
from algolia.upload import create

class CompleteFoodView(View):
    model = WikiFood
    template_name = 'review/complete_food.html'

    def get(self, request, pk=None):

    
        pair = UsdaWikiPairing.objects.get(pk=pk)
        return render(request, self.template_name, {
            'pair': pair,
            'foodNutrients': UsdaFoodNutrient.objects.filter(usda_food=pair.usda_food),
        })

    def post(self, request, pk=None):
        print('id ---- ', request.POST.get('pair_id'))
        create(request.POST.get('pair_id'))
        return redirect(reverse_lazy('review:indexed'))


class CompletedListView(View):
    template_name = 'review/completed_foods.html'

    def get(self, request, ):
        term = self.request.GET.get('filter') or ''

        not_indexed = UsdaWikiPairing.objects.filter(indexed=False)
        completed = py_.filter(
            not_indexed, lambda pair: term.lower() in pair.wiki_food.name.lower())

        for pair in completed:
            # process the nutrition data for the template
            nutrients = {}
            for nutr in UsdaFoodNutrient.objects.filter(usda_food=pair.usda_food.fdc_id):
                key = re.sub(r'[^a-zA-Z0-9]', '', nutr.nutrient.name)
                nutrients[key] = {
                    'nutrient': nutr.nutrient.name,
                    'amount': nutr.amount,
                    'unit': nutr.nutrient.unitName,
                }

            pair.set_data('nutrients', nutrients)

        return render(request, self.template_name, {
            'completed': completed,
            'term': term
        })

    def post(self, request):
        create(request.POST.get('pair_id'))
        return redirect(reverse_lazy('review:completed'))

class IndexedListView(View):
    template_name = 'review/indexed_foods.html'
    def get(self, request):
        term = self.request.GET.get('filter') or ''
        all_indexed = UsdaWikiPairing.objects.filter(indexed=True)
        filtered_indexed = py_.filter(
            all_indexed, lambda pair: term.lower() in pair.wiki_food.name.lower())

        return render(request, self.template_name, {
            'foods': filtered_indexed,
            'term': term
        })

review/views/landing_view.py
from django.shortcuts import render
from django.views import View


class ReviewLanding(View):
    def get(self, req):
        context = {}
        return render(req, 'review/landing.html', context)

review/templates/review/complete_food.html
{% extends "base_menu.html" %}

{% block head %}
<style>
  .media-object {
    width: 70px;
  }
  .img-rounded {
    float:left; 
    margin-right:16px;
    width: 100%;
  }
  .description {
    width: 100%;
    /* white-space: nowrap; */
    overflow: hidden;
    text-overflow: ellipsis;
  }
</style>
{% endblock %}

{% block content %}


{% load stats %}
{% get_stats %}

<div class="container-fluid">
  <div class="page-header">
    <h1>Review Complete for "{{ pair.wiki_food.name }}"</h1>
  </div>

  <div class="row">

    <!-- Metadata -->
    <div class="col-xs-6">

      <div class="thumbnail">
        <img src="{{pair.wiki_food.img_src}}" alt="{{pair.wiki_food.name}}">
        <div class="caption">
          <h1>{{pair.wiki_food.name}}</h1>
          <p><a href="{{pair.wiki_food.wiki_url}}" target="_blank">Scraped from this Wikipedia page</a>.</p>
          <p>{{ pair.wiki_food.description }}</p>

                <!-- Categories -->
          <h4>Categories</h4>
          <ul class="list-group">
            {% for category in pair.wiki_food.categories.all %}
              <li class="list-group-item">
                {{category.name}}
                <!-- <a href="{% url 'review:review_landing'%}"><i class="fa fa-trash"></i></a> -->
              </li>
            {% endfor %}
          </ul>
          <div style="display: flex;">
            {% if user.is_authenticated %}
              <a class="btn btn-primary" style="margin-right: 8px;" href="{% url 'review:food_metadata' pair.wiki_food.id %}">Edit Metadata</a>

              {% if not pair.indexed %}
              <form method="POST" action="">
                {% csrf_token %}
                <input type="hidden" name="pair_id" value="{{pair.id}}">
                <input type="submit" class="btn btn-default" value="Index">
              </form>
              {% endif %}
            {% endif %}
          </div>
        </div>
      </div>

    
    </div>

    <div class="col-xs-6">

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Property</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>FDC Id</td>
            <td>{{pair.usda_food.fdc_id}}</td>
          </tr>
          <tr>
            <td>Data Source</td>
            <td>{{pair.usda_food.dataType}}</td>
          </tr>
        </tbody>
      </table>

      <br>
      <h4>Key Nutrition Data Points</h4>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Nutrient</th>
            <th>Value per 100g</th>
          </tr>
        </thead>
        <tbody>
          {% for foodNutrient in foodNutrients %}
          <tr>
            <td>{{foodNutrient.nutrient.name}}</td>
            <td>{{foodNutrient.amount}} {{foodNutrient.nutrient.unitName}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      
    </div>
  </div>
</div>
{% endblock %}

review/templates/review/indexed_foods.html
{% extends "base_menu.html" %}

{% block head %}
<style>
  .img-thumbnail {
    height: 136px;
    float: left;
    margin-right: 8px; 
  }
  .list-group-item{
    background: #f1f1f1;
    overflow: hidden;
  }
  .desc {
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 4; 
    -webkit-box-orient: vertical;
  }
  .paired-item {
    color: #333;
  }
  .paired-item:hover{
    text-decoration: none;
  }
</style>
{% endblock %}

{% block content %}


{% load stats %}
{% get_stats %}

<div class="page-header">
  <h1>Foods Index for Algolia</h1>
</div>

<form method="GET" id="search_form" action="{% url 'review:paired' %}?filter='{{ term }}'">
  {% csrf_token %}
  <div class="input-group">
    <input id="filter" name="filter" placeholder="Filter Foods" class="form-control" type="text" value="{{term}}">
    
    <span class="input-group-btn">
      <button class="btn btn-default" id="search_button"><i class="fa fa-search"></i></button>
    </span>
  </div>
  {% if term %}
    <small>filtering: "{{term}}"</small>
  {% endif %}

</form>
<br>

<ul class="list-group">
  {% for pair in foods %}
  <span class="list-group-item">
    <a class="paired-item" href="{% url 'review:paired_food' pair.id %}">
      <img src="{{pair.wiki_food.img_src}}" alt="..." class="img-thumbnail">
      <h3>{{pair.wiki_food.name}}</h3>

      <p class="desc">{{pair.wiki_food.description}}</p>
    </a>
  </span>
  <br>
  {% endfor %}
</ul>
  


{% endblock %}

review/templates/review/landing.html
{% extends "base_menu.html" %}
{% load static %}

{% block head %}

<style>
  .button-container{
    display: flex;
    width: 100%;
    gap: 36px;
    margin-top: 36px;
  }
  .big-button{
    flex: 1 1 auto;
    height: 150px;
    font-size: 36px;
    background: #5f5fa2;
    color: #fff;
    box-shadow: 0 5px 5px -3px rgb(0 0 0 / 20%), 0 8px 10px 1px rgb(0 0 0 / 14%), 0 3px 14px 2px rgb(0 0 0 / 12%);
    border: none;
    border-radius: 16px;
  }
</style>
{% endblock %}



{% block content %}

<!-- 
<div class="page-header">
  <h1>Nutrition Data Aggregator <small>What do you want to review?</small></h1>
</div> -->
{% load stats %}
{% get_stats %}


<!-- 
    <div class="row">

      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/2560px-Good_Food_Display_-_NCI_Visuals_Online.jpg" alt="A variety of foods">
          <div class="caption">
          <h3>Foods</h3>
          <p>This workflow allows me to compile food information (name, categories, nutrition, etc.) from around the web and structure it for use in my nutrition application. </p>
          <p>
            <a href="{% url 'review:wiki_foods' %}" class="btn btn-primary" role="button">Review Foods</a> 
            </p>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <img src="https://upload.wikimedia.org/wikipedia/commons/6/6d/USDA_Food_Pyramid.gif" alt="A food pyramid splitting foods into categories">
          <div class="caption">
            <h3>Food Categories</h3>
            <p>Thie workflow allows me to manages the category metadata and heirarchy</p>
            <p>
                <a href="{% url 'review:wiki_categories' %}" class="btn btn-primary" role="button">Review Categories</a> 
            </p>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <img src="https://d1csarkz8obe9u.cloudfront.net/posterpreviews/food-recipe-book-design-template-96cfa4235ae5da396de74c3bdad442f7_screen.jpg?ts=1597154519" alt="A food pyramid splitting foods into categories">
          <div class="caption">
            <h3>Recipes</h3>
            <p>(Coming soon) My plan is to scrape recipes from around the web and uses them to construct recipes in my data structure.</p>
            <p>
                <a href="#" class="btn btn-primary" role="button">Button</a> 
            </p>
          </div>
        </div>
      </div>

    </div> -->

    
    <h1>The Endgame <small>Currated data for a JavaScript-based Web Apllication</small></h1>
    <br>

    <div class="row">
      <!-- <a href="https://www.figma.com/file/Wiq12dV4ZQaoniPQDlHoSz/Prototype?node-id=1433%3A49411" class="btn btn-default" role="button" target="_blank">Design Specs</a>
      <a href="https://nate-may.com/cutcal" class="btn btn-default" role="button" target="_blank">Prototype</a> -->
      
      <div class="col-sm-6 ">
        <div class="thumbnail">
          <img src="{% static 'images/cutcal.png' %}" alt="A variety of foods">
          <div class="caption">
          <h3>Cutcal Prototype</h3>
          <p>Build in JavaScript using the Angular framework</p>
          <p>
            <a href="https://cutcal.com/calendar/month/(dmy:28-2-2020)" 
              class="btn btn-primary" role="button" target="_blank">
              Check Out Cutcal Prototype
            </a> 
          </p>
          </div>
        </div>
      </div>

      <div class="col-sm-6 ">
        <div class="thumbnail">
          <img src="{% static 'images/dietstats.png' %}" alt="A variety of foods">
          <div class="caption">
          <h3>DietStats Redesign</h3>
          <p>Designed in Figma. Still undergoing major design reiteration.</p>
          <p>
            <a href="https://www.figma.com/file/Wiq12dV4ZQaoniPQDlHoSz/Prototype" 
              class="btn btn-primary" role="button" target="_blank">
              Check Out Cutcal Prototype
            </a>
          </p>
          </div>
        </div>
      </div>

    </div>

    <!-- <a href="{% url 'review:wiki_foods' %}" class="big-button">Foods</a>
    <a href="{% url 'review:review_landing' %}" class="big-button">Categories</a> -->
  </div>

{% endblock content %}

review/templates/review/scraped_food_list.html
{% extends "base_menu.html" %}

{% block head %}
<style>
  .media-object {
    width: 70px;
  }
  .avatar{
    height: 40px;
    width: 40px;
    object-fit: cover;
    margin-right: 8px;
    border-radius: 4px;
  }
  .list-group {
    display: flex;
    flex-wrap: wrap;
  }
  .list-group-item {
    width: calc(100% / 3);
  }
</style>
{% endblock %}

{% block content %}


{% load stats %}
{% get_stats %}

<div class="media">
  <div class="media-left">
    
    <img class="media-object" alt="United States Department of Aggreculture" src="https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Wikipedia-logo-v2.svg/1200px-Wikipedia-logo-v2.svg.png">
    
  </div>
  <div class="media-body">
    <h1 class="media-heading">Food Metadata <small> Scraped from Wikipedia </small></h1>
    Many of these foods were scraped from <a href="https://en.wikipedia.org/wiki/Lists_of_foods" target="_blank">this Wikipedia page</a>.
  </div>
</div>
<br>
<form method="GET" id="search_form" action="{% url 'review:wiki_foods' %}?filter='{{ term }}'">
  {% csrf_token %}
  <div class="input-group">
    <input id="filter" name="filter" placeholder="Filter Foods" class="form-control" type="text" value="{{term}}">
    
    <span class="input-group-btn">
      <button class="btn btn-default" id="search_button"><i class="fa fa-search"></i></button>
    </span>
  </div>
  {% if term %}
    <small>filtering: "{{term}}"</small>
  {% endif %}
  <!-- <input type="submit" value="Filter results"> -->
</form>

<br>

{% if wikifood_list %}
<ul class="list-group">
  {% for food in wikifood_list %}
    <li class="list-group-item">
      <a href="{% url 'review:pair_usda' food.id %}">
        <img class="avatar" loading=lazy src="{{food.img_src}}">{{food.name}}
      </a>
    </li>
  {% endfor %}
</ul>
<p>
{% else %}
  <p>There are no foods in the database.</p>
{% endif %}
</p>

{% endblock content %}

review/templates/review/stats.html
<table class="stats-table">
  <tr>
    <td><a href="{% url 'review:batch' %}">Scrape a Food List Page</a></td>
    <td><i class="fa fa-chevron-right" aria-hidden="true"></i></td>
    <td rowspan="2"><a href="{% url 'review:wiki_foods' %}">Food Metadata <sup>{{food_meta_count}}</sup></a></td>
    <td rowspan="2"><i class="fa fa-chevron-right" aria-hidden="true"></i></td>
    <td rowspan="2"><a href="{% url 'review:paired' %}">Paired Foods <sup>{{paired}}</sup></a></td>
    <td rowspan="2"><i class="fa fa-chevron-right" aria-hidden="true"></i></td>
    <td rowspan="2"><a href="{% url 'review:indexed' %}">Indexed Foods <sup>{{indexed}}</sup></a></td>
    
  </tr>
  <tr>

    <td><a href="{% url 'review:food_scrape' %}">Scrape a Food Page</a></td>
    <td><i class="fa fa-chevron-right" aria-hidden="true"></i></td>
    
  </tr>
  <!-- <tr>
    <td><a href="{% url 'review:category_scrape' %}">Scrape Category</a></td>
    <td><i class="fa fa-chevron-right" aria-hidden="true"></i></td>
    <td><a href="{% url 'review:wiki_categories' %}">Category Metadata <sup>{{cat_meta_count}}</sup></a></td>
    <td><i class="fa fa-chevron-right" aria-hidden="true"></i></td>
  </tr> -->
</table>
<br><br>