_config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django import views as django_views

urlpatterns = [
    path('', include('review.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), 
    url(r'^jsi18n/$', django_views.i18n.JavaScriptCatalog.as_view(), name='jsi18n'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {
            'document_root': os.path.join(BASE_DIR, 'site'),
            'show_indexes': True
        },
        name='site_path'
    ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(BASE_DIR, 'review/static'),
    }),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login)))
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

foods/urls.py
from django.urls import path
from . import views

app_name = 'foods'
urlpatterns = [

    path('', views.FoodLanding.as_view(), name='food_landing'),
    # path('main/create', views.CatCreate.as_view(), name='cat_create'),
    # path('main/<int:pk>/update', views.CatUpdate.as_view(), name='cat_update'),
    # path('main/<int:pk>/delete', views.CatDelete.as_view(), name='cat_delete'),

    # path('lookup', views.BreedView.as_view(), name='breed_list'),
    # path('lookup/create', views.BreedCreate.as_view(), name='breed_create'),
    # path('lookup/<int:pk>/update', views.BreedUpdate.as_view(), name='breed_update'),
    # path('lookup/<int:pk>/delete', views.BreedDelete.as_view(), name='breed_delete')
]

review/urls.py
from django import views
from django.urls import path
from .import views

app_name = 'review'
urlpatterns = [
    path('', views.ReviewLanding.as_view(), name='review_landing'),
    path('wiki_foods', views.FoodListView.as_view(), name='wiki_foods'),
    path('wiki_food/<int:pk>', views.FoodMetadataUpdate.as_view(), name='food_metadata'),
    path('pair_usda/<int:pk>', views.UsdaPairingView.as_view(), name='pair_usda'),

    path('wiki_categories', views.CategoriesListView.as_view(), name='wiki_categories'),
    path('wiki_category/<int:pk>', views.CategoryMetadataUpdate.as_view(), name='wiki_category'),

    path('pair/<int:pk>', views.PairedFoodView.as_view(), name='paired_food'),
    path('paired', views.PairedListView.as_view(), name='paired'),
    path('indexed', views.IndexedListView.as_view(), name='indexed'),
    
    path('food_scrape', views.ScrapeFood.as_view(), name='food_scrape'),
    path('category_scrape', views.ScrapeCategories.as_view(), name='category_scrape'),
    path('category_scrape/<int:pk>', views.ScrapeCategory.as_view(), name='test'),
    path('batch', views.Batch.as_view(), name='batch'),
    path('todos', views.TodoPage.as_view(), name='todos'),
]

review/views/complete_views.py
import re
from django.shortcuts import redirect, render
from django.urls.base import reverse_lazy
from django.views import View
from review.models import UsdaFoodNutrient, UsdaWikiPairing, WikiFood
from pydash import py_
from algolia.upload import create

class CompleteFoodView(View):
    model = WikiFood
    template_name = 'review/complete_food.html'

    def get(self, request, pk=None):

    
        pair = UsdaWikiPairing.objects.get(pk=pk)
        return render(request, self.template_name, {
            'pair': pair,
            'foodNutrients': UsdaFoodNutrient.objects.filter(usda_food=pair.usda_food),
        })

    def post(self, request, pk=None):
        print('id ---- ', request.POST.get('pair_id'))
        create(request.POST.get('pair_id'))
        return redirect(reverse_lazy('review:indexed'))


class CompletedListView(View):
    template_name = 'review/completed_foods.html'

    def get(self, request, ):
        term = self.request.GET.get('filter') or ''

        not_indexed = UsdaWikiPairing.objects.filter(indexed=False)
        completed = py_.filter(
            not_indexed, lambda pair: term.lower() in pair.wiki_food.name.lower())

        for pair in completed:
            # process the nutrition data for the template
            nutrients = {}
            for nutr in UsdaFoodNutrient.objects.filter(usda_food=pair.usda_food.fdc_id):
                key = re.sub(r'[^a-zA-Z0-9]', '', nutr.nutrient.name)
                nutrients[key] = {
                    'nutrient': nutr.nutrient.name,
                    'amount': nutr.amount,
                    'unit': nutr.nutrient.unitName,
                }

            pair.set_data('nutrients', nutrients)

        return render(request, self.template_name, {
            'completed': completed,
            'term': term
        })

    def post(self, request):
        create(request.POST.get('pair_id'))
        return redirect(reverse_lazy('review:completed'))

class IndexedListView(View):
    template_name = 'review/indexed_foods.html'
    def get(self, request):
        term = self.request.GET.get('filter') or ''
        all_indexed = UsdaWikiPairing.objects.filter(indexed=True)
        filtered_indexed = py_.filter(
            all_indexed, lambda pair: term.lower() in pair.wiki_food.name.lower())

        return render(request, self.template_name, {
            'foods': filtered_indexed,
            'term': term
        })

review/views/landing_view.py
from django.shortcuts import render
from django.views import View


class ReviewLanding(View):
    def get(self, req):
        context = {}
        return render(req, 'review/landing.html', context)

review/views/paired_views.py
import re
from django.shortcuts import redirect, render
from django.urls.base import reverse_lazy
from django.views import View
from review.models import UsdaFoodNutrient, UsdaWikiPairing, WikiFood
from pydash import py_
from algolia.upload import create
from django.contrib.auth.mixins import LoginRequiredMixin

class PairedFoodView(LoginRequiredMixin, View):
    model = WikiFood
    template_name = 'review/paired_food.html'

    def get(self, request, pk=None):
        pair = UsdaWikiPairing.objects.get(pk=pk)
        print(';jhvadjlhvadjv')
        print(pair.wiki_food)
        print(pair.usda_food)
        return render(request, self.template_name, {
            'pair': pair,
            'foodNutrients': UsdaFoodNutrient.objects.filter(usda_food=pair.usda_food),
        })

    def post(self, request, pk=None):
        create(request.POST.get('pair_id'))
        return redirect(reverse_lazy('review:indexed'))


class PairedListView(LoginRequiredMixin, View):
    template_name = 'review/paired_foods.html'

    def get(self, request, ):
        term = self.request.GET.get('filter') or ''

        not_indexed = UsdaWikiPairing.objects.filter(indexed=False)
        paired = py_.filter(
            not_indexed, lambda pair: term.lower() in pair.wiki_food.name.lower())

        for pair in paired:
            # process the nutrition data for the template
            nutrients = {}
            for nutr in UsdaFoodNutrient.objects.filter(usda_food=pair.usda_food.fdc_id):
                key = re.sub(r'[^a-zA-Z0-9]', '', nutr.nutrient.name)
                nutrients[key] = {
                    'nutrient': nutr.nutrient.name,
                    'amount': nutr.amount,
                    'unit': nutr.nutrient.unitName,
                }

            pair.set_data('nutrients', nutrients)

        return render(request, self.template_name, {
            'paired': paired,
            'term': term
        })

    def post(self, request):
        create(request.POST.get('pair_id'))
        return redirect(reverse_lazy('review:paired'))

class IndexedListView(LoginRequiredMixin, View):
    template_name = 'review/indexed_foods.html'
    def get(self, request):
        term = self.request.GET.get('filter') or ''
        all_indexed = UsdaWikiPairing.objects.filter(indexed=True)
        filtered_indexed = py_.filter(
            all_indexed, lambda pair: term.lower() in pair.wiki_food.name.lower())

        return render(request, self.template_name, {
            'foods': filtered_indexed,
            'term': term
        })

review/views/scrape_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import  redirect, render
from django.urls import reverse_lazy
from django.views import View
from review.forms import CatScrapableForm, ScrapeFoodForm, QuickScrapeCategoryForm
from review.models import Scrapable, WikiCategoryAssignment, WikiFood, WikiCategory
import json
from wikipedia import single_table_category, table_categories, ul_categories, food_page, helpers
import os

class ScrapeFood(LoginRequiredMixin, View):
    template_name = 'review/new_food_scrape.html'

    def get(self, request):
        return render(request, self.template_name, {'form': ScrapeFoodForm()})

    def post(self, request):

        # food = get_object_or_404(WikiFood, id=pk)
        form = ScrapeFoodForm(request.POST)

        if not form.is_valid():
            print('not valid')
            return render(request, self.template_name, {'form': form})

        food = food_page.scrape_wiki_food(request.POST.get('url'))

        return redirect(reverse_lazy('review:pair_usda', kwargs={'pk': food.id}))


class ScrapeCategories(LoginRequiredMixin, View):
    template_name = 'review/new_category_scrape.html'

    def get(self, request):
        return render(request, self.template_name, {'form': QuickScrapeCategoryForm()})

    def post(self, request):

        # food = get_object_or_404(WikiFood, id=pk)
        form = QuickScrapeCategoryForm(request.POST)

        if not form.is_valid():
            return render(request, self.template_name, {'form': form})

        stype = request.POST.get('category_scrape_type')
        url = request.POST.get('url')
        name = request.POST.get('name')
        
        if stype == 'table':
            single_table_category.scrape_page(url, name)
        elif stype == 'tables':
            table_categories.scrape_page(url, 1)
        elif stype == 'list':
            ul_categories.scrape_page(url)
        elif stype == 'single':
            cat, created = WikiCategory.objects.get_or_create(
                name=name,
                description = helpers.scape_description(url),
                wiki_url = url,
            )
            if created: cat.save()
            

        return redirect(reverse_lazy('review:category_scrape'))


class ScrapeCategory(LoginRequiredMixin, View):
    def post(self, request, pk=None):
        scrape(pk)
        return redirect(reverse_lazy('review:batch'))

class Batch(LoginRequiredMixin, View):

    def get(self, request):

        return render(request, 'review/batch.html', {
            'pages': Scrapable.objects.filter(isCategory=True, scraped=False),
            'form': CatScrapableForm(),
        })

    def post(self, request, pk=None):
        filename = '/Users/nathanielmay/Code/python/review/wikipedia/scrappable.json'
        
        scrappables = open(filename, 'r')
        cache_contents = scrappables.read()
        dumped_json_cache = json.loads(cache_contents)
        scrappables.close()

        new_scrappable = Scrapable(
            name = request.POST.get('name'),
            url = request.POST.get('url'),
            column = request.POST.get('column'),
            type  = request.POST.get('type'),
        )
        new_scrappable.save()

        dumped_json_cache['category_pages'].append([
            new_scrappable.name, 
            new_scrappable.url, 
            new_scrappable.type, 
            new_scrappable.column
        ])

        scrappables = open(filename, "w")
        scrappables.write(json.dumps(dumped_json_cache))
        scrappables.close()

        return redirect(reverse_lazy('review:batch'))


class ScrapeCategory(View):
    def get(self, request, pk=None):
        scrape(pk)
        return redirect(reverse_lazy('review:batch'))


def scrape(pk):

    page = Scrapable.objects.get(pk=pk)

    if page.type == 'single_table_category':
        single_table_category.scrape_page(page.url, page.name)

    elif page.type == 'table_categories':
        table_categories.scrape_page(page.url, page.column, page.name)

    elif page.type == 'ul_categories':
        ul_categories.scrape_page(page.url, page.name)

    page.scraped = True
    page.save()


def save_categories(categories, name):
    for scraped_cat in categories:
        category = WikiCategory(
            name=name,
            description=scraped_cat.get('description'),
            wiki_url=scraped_cat.get('wiki_url')
        )
        category.save()

        if scraped_cat.get('foods'):
            for scraped_food in scraped_cat.get('foods'):
                food = WikiFood(
                    name=scraped_food.name,
                    description=scraped_food.description,
                    wiki_url=scraped_food.image_src,
                    img_src=scraped_food.wiki_url,
                )
                food.save()
                WikiCategoryAssignment(
                    food=food,
                    category=category
                )

review/views/todo_views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin


class TodoPage(LoginRequiredMixin, View):
    def get(self, req):
        return render(req, 'review/todo.html', {
            'todos': [
                {
                    'task': 'Improve scraping',
                    'children': [
                      'Scrape names from url fragments',
                      'Look for common name and scientific name',
                      'Refined the description scrape to remove pronunciation ugliness',
                      'Figure out why some foods are duplicate',
                      'Non-destructive page scraping',
                      'Fix mushroom scrape'
                    ]
                },
                {
                    'task': 'Find more souces of food data',
                    'children': [
                      'Check data policy after IP class',
                      'Store alternative names and descriptions',
                    ]
                },
                {
                    'task': 'Images',
                    'children': [
                      'Create Images table'
                      'Add more photo API',
                      'Auto crop?',
                    ]
                },
                {
                    'task': 'Use Machine Learning to:',
                    'children': [
                      'Pick the best Image',
                      'Pick the best Name',
                      'Pick the best Description',
                      'Pair the nutrition data'
                    ]
                },
                {
                    'task': 'Algolia / Index',
                    'children': [
                       'Add categories to index',
                       'Add non-destructive update option'
                    ]
                },
                {
                    'task': 'Batch',
                    'children': [
                      'Make batch scraping non-blocking',
                      'Provide some sort of loading indcator or bage icon to indicate complete'
                    ]
                },
                {
                    'task': 'Scrape recipes',
                    'children': [
                      'Pair the recipe ingrediaents with foods',
                      'Use recipes to determine default food portion'
                    ]
                },
            ]
        })

review/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta name="dj4e" content="ea6df5245ddb26d2985ac95c87fad84a">

<meta name="dj4e-code" content="42161627484138">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>
    

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<style>
    .stats-table td {
        padding: 4px 12px;
    }
</style>
{% block head %} {% endblock %}

</head>
<body>
    <div class="container">
    {% block navbar %} {% endblock %}
    {% block welcome %} {% endblock %}
    {% block messages %}
        {% if messages %}
        {% for msg in messages %}
            <div class="alert alert-{{msg.level_tag}}" role="alert">
            {{msg.message}}
            </div>
        {% endfor %}
        {% endif %}
    {% endblock %}
    {% block content %}{% endblock %}
    </div>
{% block footer %} {% endblock %}
</body>
</html>

review/templates/base_menu.html
{% extends "base_bootstrap.html" %}

{% block navbar %}
{% load app_tags %}
<nav class="navbar navbar-default navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
        </div>
        <ul class="nav navbar-nav">
            <li {% if request.get_full_path == review %}class="active"{% endif %}>
                <a href="https://github.com/NateMay/review" target="_blank"><i class="fa fa-github fa-lg" style="margin: 4px;"></i></a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}

            <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                    <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'review:batch' %}">Scrape List</a></li>
                    <li><a href="{% url 'review:food_scrape' %}">Scrape a Food</a></li>
                    <li><a href="{% url 'review:category_scrape' %}">Scrape a Category</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'review:wiki_foods' %}">Food Metadata</a></li>
                    <li><a href="{% url 'review:wiki_categories' %}">Category Metadata</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'review:paired' %}">Paired</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'review:indexed' %}">Indexed</a></li>
                    <li><a href="https://nate-may.com/food-review" target="_blank">Live Demo</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'review:todos' %}">To Do List</a></li>
                    <li><a href="{% url 'logout' %}?next={% url 'review:review_landing' %}">Logout</a></li>
                </ul>
            </li>
            {% else %}
            <li><a href="{% url 'login' %}?next={% url 'review:review_landing' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
{% endblock %}